name: My Workflow File
on:
  push: 
    branches: [main]

jobs:
  builds:
    runs-on: Ubuntu-16.04

    steps:
    - name: greeting steps
      run: |
        echo "Hello there"

    - name: Checkout my codes
      uses: actions/checkout@v4
    - name: print content
      run:
        ls

    - name: Installing Python
      uses: actions/checkout@v4
      with:
        python-version: '3.10'
    - name: check version of python
    - run:
        python --version
