name: My second workflow  

on:
  pull_request:
    branches: [main]

jobs: 
  builds:
    runs-on: Ubuntu-20.04

    steps: 
    - name: greeting steps
      run:
        echo "Hello there"

    - name: Checkout my codes
      uses: actions/checkout@v4
    - name: print content 
      run: 
        ls 

    # this is where i install python
    - name: Installing python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: check version of python 
      run: 
         python --version 

    # installing dependencies if any
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov

    # begin test #
    - name: Begin test 
      run: |
        pytest -v -cov --junitxml=report.xml

    # this is where we access the hidden repo
    - name: Checkout Hidden Repo
      uses: actions/checkout@v4
      with:
        repository: weijun-aw/UOBHidden
        path: hiddentext
        token: ${{ secrets.DEVOPS }}

    # this prints out the hidden files
    - name: print out hidden things
      run: |
        ls
        cd hiddentext
        ls

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          *.xml
